version: "3"
services:
  jenkins:
    build: .
    image: boonchu/jenkins:lts-k8s
    ports: 8080:8080
    container_name: jenkins-sci
    environment:
      ADMIN_USER: "admin"
      ADMIN_PASSWORD: "admin"
    networks:
      - jenkins-net
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home

networks:
  jenkins-net:

volumes:
  jenkins-data:
