apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-k8s-deployment
  labels:
    app: jenkins-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-k8s
  template:
    metadata:
      labels:
        app: jenkins-k8s
    spec:
      containers:
      - name: jenkins-k8s
        image: boonchu/jenkins:lts-k8s
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: docker-sock-volume
          mountPath: /var/run/docker.sock
        - name: jenkins-home
          mountPath: "/var/jenkins_home"
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-k8s-claim
      - name: docker-sock-volume
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-k8s-service
spec:
  type: NodePort
  selector:
    app: jenkins-k8s
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
#
# https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistent-volumes
# 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-nfs-1
  labels:
    type: nfs
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-storage
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /var/nfs/kube
    server: 10.0.2.70
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-k8s-claim
  labels:
    type: nfs
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 1Gi
