apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hello-world
  name: hello-world
spec:
  containers:
  - image: docker.io/boonchu/docker_lab2:v2
    name: hello-world
    imagePullPolicy: Always
    command: ['/bin/sh', '-c', '/hello && tailf /dev/null']
  dnsPolicy: ClusterFirst
