apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: http-app
  name: http-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: http-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: http-app
        app: python-web
    spec:
      containers:
      - image: docker.io/boonchu/http_lab2:v1
        imagePullPolicy: Always
        name: http-app
        command: ['/bin/sh', '-c', '/app/start_http.sh']
        resources: {}
status: {}
