apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  labels:
    run: batch-job-sample
  name: batch-job-sample
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: batch-job-sample
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - exit 1
        image: busybox
        imagePullPolicy: Always
        name: batch-job-sample
        resources: {}
      restartPolicy: Never
status: {}
