apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: django-gunicorn
  name: django-gunicorn
spec:
  replicas: 1
  selector:
    matchLabels:
      run: django-gunicorn
  template:
    metadata:
      labels:
        run: django-gunicorn
    spec:
      containers:
      - image: boonchu/django-gunicorn
        name: django-gunicorn
        ports:
        - containerPort: 4000
        volumeMounts:
        - mountPath: "/code/static"
          name: nfs-pvc-volume-claim
        imagePullPolicy: Always
      volumes:
      - name: nfs-pvc-volume-claim
        persistentVolumeClaim:  
          claimName: nfs-pvc-vol1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: django-gunicorn
  name: django-gunicorn
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    run: django-gunicorn
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-vol1
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-storage
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/nfs/kube
    server: 10.0.2.70
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc-vol1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-storage
