version: '3'
services:
  django:
    build: .
    image: boonchu/django-gunicorn
    labels:
      - kompose.service.type=NodePort
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - 4000:4000
    networks:
      - nginx_network

  nginx:
    image: nginx:1.13
    ports:
      - 8001:80
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - static_volume:/code/static
    depends_on:
      - django
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

volumes:
  static_volume:
